(source melpa)

(package "msf.el" "1.0.0" "The Metasploit Framework Emacs interfaces.")
(package "exploitdb.el" "1.0.0" "The ExploitDB Emacs interfaces.")

(depends-on "helm")
(depends-on "emamux")
(depends-on "popwin")
